export const appRoutes = {
  authCode: '/auth/confirm',
  employeeAdmin: '/employee/admin',
  employeeAdminCampaigns: '/employee/admin/campaigns',
  employeeAdminEmployees: '/employee/admin/employees',
  employeeAdminStudents: '/employee/admin/students',
  employeeAdminDocuments: '/employee/admin/documents',
  employeeAdminDisciplines: '/employee/admin/disciplines',
  employeeAuth: '/employee/auth',
  employeeNotifications: '/employee/notifications',
  employeePersonalData: '/employee/personal-data',
  employeeSettings: '/employee/settings',
  employeeSessionContext: '/employee/session-context',
  employeeStudentApplicationDetails: '/employee/applications/details',
  employeeStudentApplications: '/employee/applications',
  employeeStudentApplicationsMine: '/employee/applications/mine',
  employeeStatistics: '/employee/statistics',
  studentAuth: '/student/auth',
  studentApplicationCreate: '/student/applications/new',
  studentDashboard: '/student/dashboard',
  studentDocuments: '/student/documents',
  studentNotifications: '/student/notifications',
  studentPersonalData: '/student/personal-data',
  studentSettings: '/student/settings',
} as const
